// For User Action/Reducer Type
export const USER_TYPE = {
  UPDATE_STATE: 'UPDATE_USER_STATE',


  LOGIN_USER: 'LOGIN_USER',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILUTE: 'LOGIN_USER_FAILUTE',

  REGISTER_USER: 'REGISTER_USER',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',

  SEND_OTP: 'SEND_OTP',
  SEND_OTP_SUCCESS: 'SEND_OTP_SUCCESS',
  SEND_OTP_FAILURE: 'SEND_OTP_FAILURE:',

  VERIFY_OTP: 'VERIFY_OTP',
  VERIFY_OTP_SUCCESS: 'VERIFY_OTP_SUCCESS',
  VERIFY_OTP_FAILURE: 'VERIFY_OTP_FAILURE',

  VERIFY_EMAIL: 'VERIFY_EMAIL',
  VERIFY_EMAIL_SUCCESS: 'VERIFY_EMAIL_SUCCESS',
  VERIFY_EMAIL_FAILURE: 'VERIFY_EMAIL_FAILURE',

  VERIFY_NUMBER: 'VERIFY_NUMBER',
  VERIFY_NUMBER_SUCCESS: 'VERIFY_NUMBER_SUCCESS',
  VERIFY_NUMBER_FAILURE: 'VERIFY_NUMBER_FAILURE',
};


export const NAV_TYPE = {
  UPDATE_STATE: 'UPDATE_NAV_STATE',

  NAV_HOME: 'NAV_HOME',

}