// For User Action/Reducer Type
export const USER_TYPE = {
  LOGIN_USER: 'LOGIN_USER',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILUTE: 'LOGIN_USER_FAILUTE',

  REGISTER_USER: 'REGISTER_USER',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAILUTE: 'REGISTER_USER_FAILUTE',
};