// For User Action/Reducer Type
export const USER_TYPE = {
  UPDATE_STATE: 'UPDATE_USER_STATE',

  CHECK_NUMBER: 'CHECK_NUMBER',
  CHECK_NUMBER_SUCCESS: 'CHECK_NUMBER_SUCCESS',
  CHECK_NUMBER_FAILURE: 'CHECK_NUMBER_FAILURE',


  LOGIN_USER: 'LOGIN_USER',
  LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILUTE: 'LOGIN_USER_FAILUTE',

  REGISTER_USER: 'REGISTER_USER',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',

  SEND_OTP: 'SEND_OTP',
  SEND_OTP_SUCCESS: 'SEND_OTP_SUCCESS',
  SEND_OTP_FAILURE: 'SEND_OTP_FAILURE:',

  VERIFY_OTP: 'VERIFY_OTP',
  VERIFY_OTP_SUCCESS: 'VERIFY_OTP_SUCCESS',
  VERIFY_OTP_FAILURE: 'VERIFY_OTP_FAILURE',

  VERIFY_EMAIL: 'VERIFY_EMAIL',
  VERIFY_EMAIL_SUCCESS: 'VERIFY_EMAIL_SUCCESS',
  VERIFY_EMAIL_FAILURE: 'VERIFY_EMAIL_FAILURE',

  VERIFY_NUMBER: 'VERIFY_NUMBER',
  VERIFY_NUMBER_SUCCESS: 'VERIFY_NUMBER_SUCCESS',
  VERIFY_NUMBER_FAILURE: 'VERIFY_NUMBER_FAILURE',
};

export const DOCTOR_TYPE = {
  UPDATE_STATE: 'UPDATE_DOCTOR_STATE',

  SEARCH_DOCTORS: 'SEARCH_DOCTORS',
  SEARCH_DOCTORS_SUCCESS: 'SEARCH_DOCTORS_SUCCESS',
  SEARCH_DOCTORS_FAILURE: 'SEARCH_DOCTORS_FAILURE',

};

export const COMMON_TYPE = {
  UPDATE_STATE: 'UPDATE_COMMON_STATE',

  GET_SPECIALITIES: 'GET_SPECIALITIES',
  GET_SPECIALITIES_SUCCESS: 'GET_SPECIALITIES_SUCCESS',
  GET_SPECIALITIES_FAILURE:'GET_SPECIALITIES_FAILURE',

  GET_HOSPITALS: 'GET_HOSPITALS',
  GET_HOSPITALS_SUCCESS: 'GET_HOSPITALS_SUCCESS',
  GET_HOSPITALS_FAILURE: 'GET_HOSPITALS_FAILURE',

  GET_COUNTRIES: 'GET_COUNTRIES',
  GET_COUNTRIES_SUCCESS: 'GET_COUNTRIES_SUCCESS',
  GET_COUNTRIES_FAILURE: 'GET_COUNTRIES_FAILURE',
  
};

export const NAV_TYPE = {
  UPDATE_STATE: 'UPDATE_NAV_STATE',

  NAV_HOME: 'NAV_HOME',

};